### ISSUE TITLE
just randomly checked out your bot

### ISSUE THREAD

**Issue by KasperBosteels** [DiamondPRO02/Femboi_OwO#2]
Hello there, so i just checked out your bot and attempted to install it.
But for some reason your bot seems to be over 100gb in modules...
-_-
bro, what?
![image](https://user-images.githubusercontent.com/55544564/159925265-27c4b320-817f-4447-bd95-413c17452418.png)
I have no idea if this is an issue with my computer or packages.
but now you know.

**Comment by DiamondPRO02** [comment]
That's weird as I'm 100% sure it's not a 100gb. At the moment I'm writing not home but I will look into this.

**Comment by DiamondPRO02** [comment]
I checked and I'm sure it's not my bot.
![image](https://user-images.githubusercontent.com/53056204/160130468-22935640-48ff-4d1f-8060-fbb011544617.png)
